name: Afk
version: 2.0.0
main: NewTheBuilder\AFK\Main
api: 4.0.0
author: NewTheBuilder
permissions:
  afk.command.use:
    default: op
    description: "Allow accès at the /afk command"
  afk.bypass:
    default: op
    description: "ByPass AFK mode."
